services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    command:  "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      web:
        condition: service_healthy
  
  web:
    build: .
    restart: always
    expose:
      - "5000"
    env_file:
     - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s