# Generated by Django 5.2.4 on 2025-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isChecked',
            field=models.BooleanField(default=False, verbose_name='Выполнил'),
        ),
    ]
