# Generated by Django 6.0.2 on 2026-03-21 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 9, 57, 28, 133141), verbose_name='Время создания'),
        ),
    ]
