# Generated by Django 6.0.2 on 2026-03-28 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_created_at_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 10, 32, 41, 105450), verbose_name='Время создания'),
        ),
    ]
