# Generated by Django 6.0.2 on 2026-04-18 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_stars_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 10, 3, 53, 264340), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 10, 3, 53, 263913), verbose_name='Время создания'),
        ),
    ]
