# Generated by Django 6.0.2 on 2026-04-18 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_created_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 10, 30, 15, 576493), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 10, 30, 15, 576110), verbose_name='Время создания'),
        ),
    ]
